name: FX Demos Build
on: [push]

jobs:
  build_deploy:
    runs-on: ubuntu-latest
    env:
        APP_PATH: "/fx-demos/"
    steps:
      - uses: actions/checkout@master
      - name: Build
        uses: TartanLlama/actions-eleventy@master
        with:
          install_dependencies: true
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: docs 
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}